/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ns.api;

import com.google.gson.JsonArray;
import ns.api.Helper.Apicaller;

public class NsApi {
    private Apicaller apicaller;
    private String apiKey;

    public NsApi(String apiKey) {
        this.apiKey = apiKey;

    }

    public NsApi() {

    }

    public boolean someLibraryMethod() {
        return  true;
    }

    public JsonArray getStations() {
        return null;
    }
}
