/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ns.api;

import com.google.gson.JsonArray;
import ns.api.Helper.Apicaller;

public class Library {
    private Apicaller apicaller;
    public boolean someLibraryMethod() {
        return true;
    }

    public JsonArray getStations(){
        return null;
    }

    public Library(String apikey){

    }
}
